# Default
baseURL = "https://hervyqa.id/"
title = "Hervy Qurrotul Ainur - Free Software & Multimedia"
languageName = "Id"
languageCode = "id-id"
# post pagination
paginate = "8"
# post excerpt
summaryLength = "15"
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "hervyqa" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # example: ["fr"] for disable french language
timeout = 60000
#buymeacoffeeid = ""
#adsensedataadclient = ""
#discussionid = ""
rssLimit = 20

# Modules
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

# Outputs
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

# Imaging
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90

# Caches
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

# Markup
[markup]
[markup.goldmark.renderer]
unsafe = true

# Media types
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

# Output Format
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
