# Default
baseURL = "https://hervyqa.id/"
title = "Data Enthusiast & Free Software"
languageName = "Id"
languageCode = "id-id"
paginate = "8"
summaryLength = "15"
disableLanguages = ["fr"] # example: ["fr"] for disable french language
timeout = 60000
buymeacoffeeid = ""
adsensedataadclient = ""
# disqusShortname = "hervyqa"
# googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
rssLimit = 20

[params.giscus]
repo = "hervyqa/website"
repoID = "R_kgDOI2ly8Q"
category = "General"
categoryID = "DIC_kwDOI2ly8c4CT10N"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "preferred_color_scheme"
# theme = "light"
lang = "en"
loading = "lazy"

# Modules
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

# Outputs
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

# Imaging
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 75

# Caches
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

# Markup
[markup]
[markup.goldmark.renderer]
unsafe = true

# Media types
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

# Output Format
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
