# default parameters

# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "60x"
# logo text will only show when logo is missing.
logo_text = "Hervy Qurotul Ainur"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Seputar data science dengan perangkat lunak bebas."
author = "Hervy Qurrotul Ainur"
image = "images/index.jpg" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Ds. Kembangsri, RT 02/02, </br>Kec. Ngoro, Mojokerto,<br>Jawa Timur."
mobile = "+6281336762725"
email = "hervyqa@proton.me"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# featured post title

featured_post_title = "Unggulan"
recent_post_title = "Terbaru"
mainSections = ["blog"]
# about widget content
about_widget_content = "Seputar data science dengan perangkat lunak bebas."
# footer content
footer_content = "Seputar data science dengan perangkat lunak bebas."
# copyright
copyright = "Copyright © 2019-2023 [Hervy Qurrotul Ainur](https://hervyqa.id).</br>Content is [CC BY-SA 4.0.](https://creativecommons.org/licenses/by-sa/4.0/) & Developed by [Statichunt](https://statichunt.com/)."

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script= ""

[permalinks]
  blog = '/:slug'
  categories = '/:slug'

# preloader

[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# banner

[banner]
enable = true
title_large = "Hervy Q. A."
title_small = "Data Science &<br>Free Software"
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
content = "Data Enthusiast, Tech Writer & Creator [**LangitKetujuh OS**](https://langitketujuh.id)"
button_label = "Blog"
button_link = "blog"
#button_label_aditional = "Buy Me Coffe"
#button_link_aditional = "buymecoffe"

# advertise

[advertisement]
enable = false
image = "images/promotion.png"
link = "https://langitketujuh.id/"

# cookies

[cookies]
enable = false
expire_days = 2
content = "Situs ini menggunakan cookie. Dengan terus menggunakan situs web ini, Anda menyetujui penggunaannya."
button = "Saya Setuju"

# sidebar widgets

[widgets]
sidebar = ["about", "newsletter", "recent-post", "categories"]
# available widget : about,categories,newsletter,recent-post


# subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "#" # ex:https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074 replace this url with yours
mailchimp_form_name = "#" # ex:b_463ee871f45d2d93748e77cad_a0a2c6d074 replace this code with yours


############################# social site ########################
[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/hervyqa/"

[[social]]
title = "sourcehut"
icon = "fa-brands fa-git-alt"
link = "https://sr.ht/~hervyqa"

[[social]]
title = "github"
icon = "fab fa-github"
link = "https://github.com/hervyqa"

[[social]]
title = "gitlab"
icon = "fab fa-gitlab"
link = "https://gitlab.com/hervyqa"

[[social]]
title = "telegram"
icon = "fab fa-telegram"
link = "https://t.me/hervyqa"

[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://fb.com/hervyqa"

[[social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/hervyqa"

[[social]]
title = "instagram"
icon = "fab fa-instagram"
link = "https://instagram.com/hervyqa"

# [[social]]
# title = "feed rss"
# icon = "fa fa-rss"
# link = "https://hervyqa.id/index.xml"
