# default parameters

# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "60x"
# logo text will only show when logo is missing.
logo_text = "Hervy Qurotul Ainur"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Kreator LangitKetujuh OS untuk Multimedia. Generalis Desain Layout (Scribus), Animasi (Blender3D), Pattern, Logo, Branding, Ilustrasi (Inkscape & Krita) dan Template Dokumen (LibreOffice). Serta Kontributor dibeberapa komunitas besar GNU/Linux."
author = "Hervy Qurrotul Ainur"
image = "images/index.jpg" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Jalan Raya Ngoro, RT 02/02,<br>Desa Kembangsri, Ngoro,<br>Mojokerto, Jawa Timur."
mobile = "+6281336762725"
email = "hervyqa@proton.me"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# featured post title

featured_post_title = "Posting Unggulan"
recent_post_title = "Posting Terbaru"
mainSections = ["blog"]
# about widget content
about_widget_content = "Seputar perangkat lunak bebas untuk multimedia dengan perangkat lunak bebas GNU/Linux."
# footer content
footer_content = "Seputar perangkat lunak bebas untuk multimedia dengan perangkat lunak bebas GNU/Linux."
# copyright
copyright = "© 2019-2022 | [Hervy Qurrotul Ainur](https://hervyqa.id)<br>& Developed by [Statichunt](https://statichunt.com/)."

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script= ""

[permalinks]
  blog = '/:slug'
  categories = '/:slug'

# preloader

[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# banner

[banner]
enable = true
title_large = "Hervy Qurrotul Ainur"
title_small = "Free Software &<br>Multimedia"
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
#content = "Kreator **[LangitKetujuh OS](https://langitketujuh.id)** untuk multimedia. Fokus di branding, animasi, desain grafis dan tekstil. Bagian dari **[Mentari Umsida](https://mentari.umsida.ac.id)**, **[PCPM Ngoro](https://pcpmngoro.or.id)**, Masjid **[Al-Mujahidin](https://almujahidinkembangsri.or.id)**, Travel **[WahyuTrans](https://wahyutranstravel.com)** dan jago masak di **[Bu Win Katering](https://buwinkatering.com)**."
content = "Kreator [**LangitKetujuh OS**](https://langitketujuh.id) untuk Multimedia. Generalis Desain Layout ([Scribus](https://scribus.net)), Animasi ([Blender3D](https://blender.org)), Pattern, Logo, Branding, Ilustrasi ([Inkscape](https://inkscape.org) & [Krita](https://krita.org)) dan Template Dokumen ([LibreOffice](https://libreoffice.org))."
button_label = "Baca blog"
button_link = "blog/"

# advertise

[advertisement]
image = "images/promotion.png"
link = "https://langitketujuh.id/"

# cookies

[cookies]
enable = false
expire_days = 2
content = "Situs ini menggunakan cookie. Dengan terus menggunakan situs web ini, Anda menyetujui penggunaannya."
button = "Saya Setuju"

# sidebar widgets

[widgets]
sidebar = ["about", "newsletter", "recent-post", "categories"]
# available widget : about,categories,newsletter,recent-post


# subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "#" # ex:https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074 replace this url with yours
mailchimp_form_name = "#" # ex:b_463ee871f45d2d93748e77cad_a0a2c6d074 replace this code with yours


############################# social site ########################
[[social]]
title = "telegram"
icon = "fab fa-telegram"
link = "https://t.me/hervyqa"

[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://fb.com/hervyqa"

[[social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/hervyqa"

[[social]]
title = "instagram"
icon = "fab fa-instagram"
link = "https://instagram.com/hervyqa"

[[social]]
title = "gitlab"
icon = "fab fa-gitlab"
link = "https://gitlab.com/hervyqa"

[[social]]
title = "feed rss"
icon = "fa fa-rss"
link = "https://hervyqa.id/index.xml"

#[[social]]
#title = "linkedin"
#icon = "fab fa-linkedin"
#link = "#"

#[[social]]
#title = "github"
#icon = "fab fa-github"
#link = "https://github.com/hervyqa"
