baseURL = "https://hervyqa.com"
languageCode = "en-us"
defaultContentLanguage = "id"
title = "Hervyqa"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true
googleAnalytics = "UA-144344761-1"
disqusShortname = "hervyqa"

[author]
  name = "Hervy Qurrotul Ainur"

[permalinks]
  posts = "/posts/:title/"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  categories = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  description = "Ulasan sederhana tentang belajar ilustrasi, tutorial semless pattern vektor, tips eps mikrostok dengan inkscape, dan tips belajar UI/X"
  keywords = "seamless, pattern, inkscape, mikrostock, ui, ux, desain, libreoffce, impress, flat, ilustrasi, git, shutterstock, 123rf, freepik, dreamstime"
  images = ""
  themeColor = "#494f5c"
  homeSubtitle = "Catatan sederhana belajar ilustrasi, pattern, vektor, inkscape, mikrostok, dan UI/X."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  justifyContent = false
  relatedPosts = true
  # bgImg = ""
  # gitUrl = "https://github.com/username/repository/commit/"
  # customCSS = ["css/foo.css", "css/bar.css"]

  [[params.social]]
    name = "shutterstock"
    url  = "http://www.shutterstock.com/g/hervyqa?rid=238649869"

  [[params.social]]
    name = "freepik"
    url  = "https://freepik.com/hervyqa"

  #[[params.social]]
    #name = "adobestock"
    #url  = "https://adobestock.com/"

  [[params.social]]
    name = "123rf"
    url  = "https://123rf.com/profile_hervyqa"

  [[params.social]]
    name = "dreamstime"
    url  = "https://dreamstime.com/hervyqa_info"

  #[[params.social]]
    #name = "dribbble"
    #url  = "https://dribbble.com/hervyqa"

  #[[params.social]]
    #name = "behance"
    #url  = "https://b.net/hervyqa"

  [[params.social]]
    name = "telegram"
    url  = "https://www.t.me/hervyqa/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/hervyqa"

  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/hervyqa"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/hervyqa"

  [[params.social]]
    name = "paypal"
    url  = "https://www.paypal.me/hervyqa"

  #[[params.social]]
    #name = "stackoverflow"
    #url  = "http://www.stackoverflow.com/"

  [[params.social]]
    name = "gitlab"
    url  = "https://www.gitlab.com/hervyqa"

  [[params.social]]
    name = "github"
    url = "https://github.com/hervyqa"

  [[params.social]]
    name = "email"
    url  = "mailto:hervyqa@gmail.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = "2"
  [[menu.main]]
    identifier = "portofolio"
    name       = "Portofolio"
    url        = "portofolio/"
    weight     = "3"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = "4"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
