# site variables

# customize your color and font from here.
[params.variables]
color_primary = "#0a8451"
body_color = "#ffffff"
text_color = "#1a1a1a"
text_dark = "#292929"
text_light = "#999999"
border_color = "#e1e1e1"
black = "#292929"
white = "#ffffff"
light = "#f2f2f2"

# font variables

# base font size for full website,
font_size = "16px" # default is 16px

# font scale sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
# font_primary = "Lora:wght@400"
# font_primary = "PT Serif:wght@400"
font_primary = "Noto Serif:wght@400"
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = "Noto Serif:wght@400;700"
font_secondary_type = "sans-serif" # [serif/sans-serif]
font_icon = "Font Awesome 6 Free"

# plugins

# css plugins
[[params.plugins.css]]
link = "plugins/font-awesome/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/fontawesome.css"
[[params.plugins.css]]
link = "plugins/font-awesome/regular.css"
[[params.plugins.css]]
link = "plugins/font-awesome/solid.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.js"
[[params.plugins.js]]
link = "plugins/search/fuse.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.js"
