baseURL = "https://hervyqa.com"
languageCode = "en"
defaultContentLanguage = "id"
title = "Hervy Q. A."
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
theme = "nuo"

# Disqus Username
disqusShortname = "hervyqa"

# Google Analytics UA number
googleAnalytics = "UA-144344761-1"

# Copyright of your post
copyright = "© Artikel ini menggunakan lisensi Creative Commons Attribution-ShareAlike 4.0 Internasional."

# Initial site menu, you can extend menu with content.

[permalinks]
  post = "/post/:title/"

[[menu.main]]
  name = "Beranda"
  weight = 10
  identifier = "beranda"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Hervy Qurrotul Ainur"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "Seamless Pattern dan Desain Grafis FLOSS Blog"
  subtitle = "~ Seamless Pattern + Ilustrasi ~"
  description = "Sebuah tempat untuk berbagi tutorial desain, produk yang baru dirilis dan ilustrasi seamless pattern, tentunya dengan memakai aplikasi FLOSS. "
  paginate = 10

  # Choose your social networks
  email = "hervyqa@gmail.com"
  github = "hervyqa"
  gitlab = "hervyqa"
  twitter = "hervyqa"
  instagram = "hervyqa"
  linkedin = "hervyqa"
  dribbble = "hervyqa"
  behance = "hervyqa"
  # weibo = "weibo_username"
  # wechat= "images/qrcode.jpg"  # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"
  # stackoverflow = "laozhu"
  # codesandbox = "melaozhu"
  # npm = "laozhu"
  # reddit = "melaozhu"

  # Overrid theme styles in this file
  # customStyle = "styles/custom.scss"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "UXccFqygQIdWT3kMzHe9tBO5_p_Z8xrC6ym2WQq2G8I"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = ""

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
