backend:
  name: git-gateway
  branch: main

logo_url : "/images/index.jpg"
media_folder: "assets/images/blog"
public_folder: "/public/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image (1920x1080 px)", name: "image", widget: "image"}
      - {
        label: 'Type',
        name: 'type',
        widget: 'select',
        options:
          [{ label: 'Featured', value: "featured" }, { label: 'Regular', value: "regular" }],
        default: ["Regular"],
        }
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Pages"
    name: "pages"
    files:
      - label: "Profil"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Cover Image (1920x1080 px)", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
