name = "friend"
license = "MIT"

[author]
  name = "Hervy Qurrotul"
  homepage = "https://hervyqa.gitlab.io"

[original]
  name = "Djordje Atlialp"
  homepage = "https://atlialp.com"
  twitter = "https://twitter.com/rhazdon"

[original]
  name = "hello-friend"
  homepage = "https://github.com/panr/hugo-theme-hello-friend"
  repo = "https://github.com/panr/hugo-theme-hello-friend"
